env: "local" # Окружение - local, dev или prod
start_urls:
  - url: "http://kremlin.ru/events/all/feed"
    lang: "ru"
  - url: "http://en.kremlin.ru/events/all/feed"
    lang: "en"
parser:
  URI: "http://kremlin.ru/events/all/feed"
  page_count: 1
  output_path: "./data"
  parse_delay: 2s
